apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kmj7bzjoq-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:13e72e3f495919784d23dc79ebee2335ef0e0d50@sha256:5c70349c44b30792f755a3e8e1ef2f4972e58298505c5b4c0c38d8d74d58f926
          name: container-image
