apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kmj7bzjoq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kmj7bzjoq-go 
  name: kmj7bzjoq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kmj7bzjoq-go 
